import Header from "@/components/Header/Header";
import "./globals.scss";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Main from "@/components/Main/Main";
import CheckMobileProvider from "@/providers/CheckMobileProvider";

const jakartaSans = Plus_Jakarta_Sans({
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
   display: "swap",
});

export const metadata: Metadata = {
   title: "Car Rent",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={jakartaSans.className}>
            <div className="flex flex-col min-h-full overflow-hidden">
               <CheckMobileProvider>
                  <Header />
                  <Main>{children}</Main>
                  <Footer />
               </CheckMobileProvider>
            </div>
         </body>
      </html>
   );
}
